CREATE table TB_POST (
	ID 					NUMBER 						PRIMARY KEY,
	TITLE 				VARCHAR(100) 	NOT NULL,
	CONTENT 			VARCHAR(300) 	NOT NULL,
	CREATE_DATE_TIME 	DATE 			NOT NULL,
	CREATOR_IP 			VARCHAR(15) 	NOT NULL,
	UPDATE_DATE_TIME 	DATE 			NULL,
	UPDATER_IP 			VARCHAR(15) 	NULL
)